language: ruby
sudo: false

cache:
  bundler: true

bundler_args: --without test --jobs 3 --retry 3

script: 'cd guides && bundle exec rake guides:generate:html'

env:
  global:
    - "GUIDES_LANGUAGE=ko"

rvm:
  - ruby-head

notifications:
  email: false
