language: ruby
sudo: false

cache:
  bundler: true

bundler_args: --without test --jobs 3 --retry 3

branches:
  only:
  - korean

script: ./deploy.sh

env:
  global:
    - "GUIDES_LANGUAGE=ko"
    - "RAILS_VERSION=v3.2.3"

rvm:
  - ruby-head

notifications:
  email: false
